#!/bin/bash

OUTPUT="components.css"

[ -f "$OUTPUT" ] && rm "$OUTPUT"

for css_file in components/*.css; do
    [ -f "$css_file" ] || continue
    cat "$css_file" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
done

echo "Done"
