#! 0-31 reserved for Igloo <-> Floe
#! 31-63 reserved for Custom Floe Commands (specified in Floe.toml)
#! 64+ reserved for Component commands

[[commands]]
name = "WhatsUpIgloo"
id = 0
desc = "Initialize communication with Igloo."
fields = [
    { name = "max_supported_component", type = "u16", desc = "Specifies the newest component you know." },
]

[[commands]]
name = "RegisterDevice"
id = 1
desc = "Floe request to register a device with Igloo"
fields = [
    { name = "device_id", type = "String", desc = "Persistent device ID. You should register the device under the same ID every boot. UUIDv7 is recommended." },
    { name = "initial_name", type = "String", desc = "Name for the device for first register. Can be modified by the user later on" },
    { name = "entity_names", type = "Vec<String>", desc = "The name of every entity you will ever have. Cannot change this after registration!" }
]

[[commands]]
name = "DeviceRegistered"
id = 2
desc = """
Igloo has confirmed the device registration. 
"""
fields = [
    { name = "id", type = "String", desc = "The ID of the device that you registered. Given for reference." },
    { name = "successful", type = "bool", desc = "If the registration was successful" },
]

[[commands]]
name = "StartTransaction"
id = 3
desc = """
Begins a transaction of component updates for an entity.
During a transaction only send component commands (64+).
All other commands will be dropped until EndTransaction is sent.

If sent from a Floe, it is confirming these changes.
If sent from Igloo, it is requesting these changed. Accept them by sending back a transaction after application.
"""
fields = [
    { name = "device_ref", type = "u16" },
    { name = "entity_ref", type = "u16" },
]

[[commands]]
name = "EndTransaction"
id = 4

[[commands]]
name = "ExecuteQuery"
id = 5
desc = """
TODO
"""

[[commands]]
name = "QueryResult"
id = 5
desc = """
TODO Probably be a transaction?? Start transaction with query ID then give parts
"""
