#! 0-31 reserved for Igloo <-> Floe
#! 32-63 reserved for Custom Floe Commands (specified in Floe.toml)
#! 64+ reserved for Component commands

[[commands]]
name = "WhatsUpIgloo"
id = 0
desc = "Initialize communication with Igloo."
fields = [
    { name = "max_supported_component", type = "u16", desc = "The newest component you know." },
]

[[commands]]
name = "CreateDevice"
id = 1
desc = "TODO"
fields = [
    { name = "name", type = "String" }
]

[[commands]]
name = "DeviceCreated"
id = 2
desc = "TODO"
fields = [
    { name = "name", type = "String", desc = "Passback" },
    { name = "id", type = "u64", desc = "Persistent reference for this device" }
]

[[commands]]
name = "StartTransaction"
id = 3
desc = "TODO"
fields = [
    { name = "device_id", type = "u64", desc = "Persistent device reference" },
]

[[commands]]
name = "EndTransaction"
id = 4
desc = "TODO"

# TODO add comments to all the following saying they must be inside transaction

[[commands]]
name = "RegisterEntity"
id = 5
desc = "TODO"
fields = [
    { name = "entity_name", type = "String" },
    { name = "entity_idx", type = "u32", desc = "Entity indexes start 0 and increment for every entity you add on the device. Pass here for validation." }
]

[[commands]]
name = "SelectEntity"
id = 6
desc = "TODO"
fields = [
    { name = "entity_idx", type = "u32" }
]

[[commands]]
name = "DeselectEntity"
id = 7
desc = "TODO"


# Placeholders
[[commands]]
name = "ExecuteQuery"
id = 8
desc = "TODO"

[[commands]]
name = "SelectQuery"
id = 9
desc = "TODO"
